version: '3.8'

services:
  frimmich:
    image: ghcr.io/jasobih/frimmich:latest # Use pre-built image from GHCR
    container_name: frimmich
    ports:
      - "8080:8080"
    environment:
      # Required Immich Configuration
      - IMMICH_API_URL=http://<your_immich_ip>:2283
      - IMMICH_API_KEY=<your_immich_api_key>
      # Required Frigate Configuration
      - FRIGATE_FACES_DIR=/app/frigate_faces
      # Optional: Scheduled Sync (set to 0 to disable)
      - SYNC_SCHEDULE_INTERVAL_HOURS=0
      # Optional: MQTT Configuration (uncomment and configure to enable)
      # - MQTT_HOST=<your_mqtt_broker_ip>
      # - MQTT_PORT=1883
      # - MQTT_USERNAME=<your_mqtt_username>
      # - MQTT_PASSWORD=<your_mqtt_password>
      # - MQTT_TOPIC_PREFIX=frimmich
      # Optional: Frigate API for restart (uncomment and configure to enable)
      # - FRIGATE_API_URL=http://<your_frigate_ip>:5000
      # Optional: Logging Level (DEBUG, INFO, WARNING, ERROR)
      - LOG_LEVEL=INFO
      # Optional: Max faces per person to sync
      - MAX_FACES_PER_PERSON=100
      # Optional: Skip already existing faces
      - SKIP_EXISTING_FACES=true
    volumes:
      # Persistent storage for synced faces state
      - ./data:/app/data
      # Mount your Frigate clips/faces directory here
      # IMPORTANT: Replace the host path with your actual Frigate faces directory
      - /mnt/frigate/clips/faces:/app/frigate_faces
    restart: unless-stopped
